from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from concurrent.futures import ThreadPoolExecutor
from gtts import gTTS
import asyncio
import logging
import os
import uuid

# Local imports
from data import run_scraper
from rag import response

# ---------------- APP INIT ----------------
app = FastAPI()

# Allow only your frontend domain
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # change to your frontend URL
    allow_methods=["*"],
    allow_headers=["*"],
)

# Thread pool for blocking tasks
executor = ThreadPoolExecutor()

# Logging config
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)


# ---------------- API ENDPOINTS ----------------
@app.get("/data")
async def get_data():
    """User-facing scraper endpoint (on-demand)."""
    return await run_scraper()


@app.post("/cron/run-scraper")
async def cron_run_scraper():
    """Dedicated endpoint for Render cron jobs."""
    logging.info("Cron job triggered: running scraper")
    return await run_scraper()


@app.post("/process_text/")
async def process_text(text: str):
    """Takes text, generates RAG response + TTS audio."""
    try:
        response_text = response(text) or "Sorry, I could not generate a response."
        filename = f"/tmp/tts_{uuid.uuid4()}.mp3"  # store in /tmp for ephemeral use

        loop = asyncio.get_event_loop()

        def tts_task():
            tts = gTTS(response_text)
            tts.save(filename)

        await loop.run_in_executor(executor, tts_task)

        return {"response_text": response_text, "audio_file": os.path.basename(filename)}
    except Exception as e:
        logging.error(f"Error in /process_text/: {e}")
        return {"response_text": "Error: Could not process request.", "audio_file": None}


@app.get("/audio/{filename}")
async def get_audio(filename: str):
    """Serve audio file generated by process_text()."""
    filepath = os.path.join("/tmp", filename)
    if os.path.exists(filepath):
        return FileResponse(filepath, media_type="audio/mpeg")
    return {"error": "File not found"}

# from fastapi import FastAPI
# from data import run_scraper
# from fastapi import FastAPI, Request
# from fastapi.responses import StreamingResponse
# import asyncio
# from fastapi.middleware.cors import CORSMiddleware
# from fastapi.responses import FileResponse

# import pyttsx3
# import uuid
# import os

# # RAG imports
# from rag import response
# import logging
# from concurrent.futures import ThreadPoolExecutor

# app = FastAPI()
# # ---------------- FASTAPI ----------------
# @app.get("/data")
# async def get_data():
#     return await run_scraper()


# # Allow CORS for Streamlit frontend
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

# # Initialize pyttsx3 TTS engine once
# tts_engine = pyttsx3.init()



# @app.post("/process_text/")
# async def process_text(text: str):
#     try:
#         # Get response from RAG
#         response_text = response(text)
#         logging.info(f"RAG response: {response_text}")
#         if not response_text:
#             response_text = "Sorry, I could not generate a response."
#         # Generate TTS audio file in a thread to avoid blocking
#         filename = f"tts_{uuid.uuid4()}.mp3"
#         loop = asyncio.get_event_loop()
#         def tts_task():
#             tts_engine.save_to_file(response_text, filename)
#             tts_engine.runAndWait()
#         await loop.run_in_executor(ThreadPoolExecutor(), tts_task)
#         return {"response_text": response_text, "audio_file": filename}
#     except Exception as e:
#         logging.error(f"Error in /process_text/: {e}")
#         return {"response_text": "Error: Could not process request.", "audio_file": None}

# @app.get("/audio/{filename}")
# async def get_audio(filename: str):
#     filepath = os.path.join(os.getcwd(), filename)
#     if os.path.exists(filepath):
#         return FileResponse(filepath, media_type="audio/mpeg")
#     return {"error": "File not found"}